<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{ReportingTools and knitr R markdown}
%\VignetteKeywords{vignette, markdown, knitr, ReportingTools}
%\VignettePackage{rauthoring}
-->

ReporingTools and knitr
========================

## Introduction

It is possible to include `ReportingTools` elements into `knitr` R
markdown documents. Compiling such documents must be done with
`knitr::knit2html` (instead of `rmarkdown::render`).

## A table

```{r, env, echo=FALSE, message=FALSE}
library("ReportingTools")
library("XML")
```

The following code chunk, with argument `results='asis'` will produce
the dynamic table below.

```{r, reptoolsknitr0, eval=FALSE}
library("ReportingTools")
library("XML")
htmlRep <- HTMLReport(shortName = "knitrReport",
                      handlers = knitrHandlers,
                      reportDirectory = ".")
htmlRep[["mtcars"]] <- mtcars  ##this line is equivalent to the line above
```

```{r, reptoolsknitr, results = 'asis', echo=FALSE}
library("ReportingTools")
library("XML")
htmlRep <- HTMLReport(shortName = "knitrReport",
                      handlers = knitrHandlers,
                      reportDirectory = ".")
htmlRep[["mtcars"]] <- mtcars  ##this line is equivalent to the line above
```
